<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eventos.DAL\Eventos.DAL.csproj" />
    <ProjectReference Include="..\Eventos.Entities\Eventos.Entities.csproj" />
    <ProjectReference Include="..\Eventos.Common\Eventos.Common.csproj" />
    <ProjectReference Include="..\Eventos.BL\Eventos.BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="7.0.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.0" />
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
  </ItemGroup>

</Project>
